<?

$prefnames = array(
	// indicates the user wants to hide content that is not safe for work
	"hide_nsfw",
	// indicates the user wants to hide content that might be offensive
	"hide_tmbo",
	// indicates if the user wants to view thumbnails in comments
	"thumbnails_in_comments",
	
	// sorting for discussions
	"disc_sortorder",
	// type of frontpage, "thumbs" or blank
	"index",
	
	// key commands:
	// vote good
	"key_good",
	// vote bad
	"key_bad",
	// go to the next post in the stream
	"key_next",
	// go to the previous post in the stream
	"key_prev",
	// go to the index
	"key_index",
	// go to the comments for this upload
	"key_comments",
	// open the quick reply window
	"key_quick",
	// close modal dialogues
	"key_escape"
    );

?>