<?

	$quips = array(
		"hug me and descend into madness",
		"if you don't understand, upload a picture of yer mom and we'll do a little experiment.",
		"welcome back. we missed you. oh, and don't use apostrophes for plurals. ever.",
		"because the only thing better than a giant robot is a GIANT ROBOT WITH BAT WINGS",
		"faking an italian accent helps if ya get busted",
		"you people are cooler than the other side of my pillow.",
		"i came for the free shit, i stay for the arrow keys.",
		"if the internet makes you mad, you are not doing it right.",
		"DON'T post your findings when you search for tubgirl",
		"holy shit, I just about killed myself! where's my camera?",
		"there's no shame in getting the fuck away from a pissed off armadillo",
		"you do not want vodka getting into your urethra. you really, really, don't.",
		"consciousness doesn't really exist. it's just another one of our ideas.",
		"time flies like an arrow, but fruit flies like a banana.",
		"bow chicka wow-wow"
	
		);
	$quip = $quips[rand(0, count($quips) - 1)];

?>