<?

$key_options = array(
	"noselect" => "Select key function...",
	"key_next" => "newer",
	"key_prev" => "older",
	"key_comments" => "comments",
	"key_index" => "index",
	"key_good" => "vote [this is good]",
	"key_bad" => "vote [this is bad]",
	"key_subscribe" => "(un)subscribe to thread",
	// XXX: pending comment joining
	// key_tmbo
	// key_tiar
	// key_pickup
	"key_quick" => "quick reply",
	"key_escape" => "close dialog",
	"key_random" => "random image"
	);

?>