<?

	$quips = array(
		"By the hairy taint of DarkStalker, I curse you all.",
		"hug me and descend into madness",
		"welcome back. we missed you. oh, and don't use apostrophes for plurals. ever.",
		"you're cooler than the other side of my pillow.",
		"consciousness doesn't really exist. it's just another one of our ideas.",
		"what did you bring the book i didn't want to be read out of up for?"
		);
	$quip = $quips[rand(0, count($quips) - 1)];

?>
